language: android
dist: trusty
android:
  components:
      - tools
      - android-25
      - build-tools-26.0.2
      - extra-android-support
      - extra-android-m2repository
before_script: 
      - cd UEE_Banking_App_Android
