language: android
dist: trusty
android:
  components:
      - tools
      - android-25
      - build-tools-26.0.2
      - extra-android-support
      - extra-android-m2repository
before_script: 
      - find . -type f -perm 755 -exec chmod 644 {} \;
      - cd UEE_Banking_App_Android
before_install:
  - wget https://services.gradle.org/distributions/gradle-5.5.1-bin.zip
  - unzip -qq gradle-5.5.1-bin.zip
  - export GRADLE_HOME=$PWD/gradle-5.5.1
  - export PATH=$GRADLE_HOME/bin:$PATH
  - gradle -v
# script:
#   - gradle

