language: android
dist: trusty
android:
  components:
      - tools
      - android-25
      - build-tools-26.0.2
before_script: 
      - cd UEE_Banking_App_Android
script:
 - chmod +x ./gradlew build connectedCheck
