language: android
dist: trusty
android:
  components:
      - tools
      - android-25
      - build-tools-26.0.2
      - extra-android-support
      - extra-android-m2repository
before_script: 
      - cd UEE_Banking_App_Android
script:
      - wget https://services.gradle.org/distributions/gradle-5.2.1-bin.zip -P /tmp
      - unzip -d /opt/gradle /tmp/gradle-*.zip
      - vi /etc/profile.d/gradle.sh
      - export GRADLE_HOME=/opt/gradle/gradle-5.2.1
      - export PATH=${GRADLE_HOME}/bin:${PATH}
      - gradle
